version: "3.9"
services:
  agent1:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-agent1
    privileged: true
    user: root
    labels:
      - "jenkins-agent=true"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    expose:
      - "32768:22"
    networks:
      - jenkins

  agent2:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-agent2
    privileged: true
    user: root
    labels:
      - "jenkins-agent=true"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    expose:
      - "32769:22"
    networks:
      - jenkins

  agent3:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-agent3
    privileged: true
    user: root
    labels:
      - "jenkins-agent=true"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    expose:
      - "32770:22"
    networks:
      - jenkins

networks:
  jenkins:
