version: "3.9"
services:
  docker:
    container_name: docker
    image: docker:dind
    privileged: true
    restart: always 
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
  jenkins:
    container_name: jenkins-n
    restart: always 
    depends_on:
      - docker
    image: enzovalentinlombardocaridad192/jenkins-ssh:latest
    user: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
    ports:
      - "8080:8080"
      - "50000:50000"
      - "4243:4243"
      - "22:22"
    networks:
      - jenkins

  socat:
    container_name: socat
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    expose:
      - "2376:2375"
    restart: always
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
